language: cpp
os: linux
dist: trusty


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:beineri/opt-qt562-trusty'
    packages:
      - qt52base
      - qt52script
      - qt52declarative
      - qt52tools
      - qt52x11extras
      - qt52svg
      - ninja-build
      - libxcb-keysyms1-dev
      - libxml2-utils
      - libudev-dev
      - texinfo

script:
  - ./build_frameworks.sh -i ~/kf5-debug -t Debug -g Ninja -o ~/kf5-gcc-linux64-debug.tar.xz
  - ./build_frameworks.sh -i ~/kf5-release -t Release -g Ninja -o ~/kf5-gcc-linux64-release.tar.xz

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash ./upload.sh ~/kf5-gcc-linux64-debug.tar.xz ~/kf5-gcc-linux64-release.tar.xz
